## Урок № 6. Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ.

### Задание № 1.
Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

**Ответ:**

In [1]:
import numpy as np

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
zp, ks

(array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110]),
 array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832]))

In [6]:
# Найдём ковариацию с помощью элементарных действий:
covariation = np.mean(zp * ks) - np.mean(zp) * np.mean(ks)
covariation, np.cov(zp, ks,ddof=0)

(9157.839999999997, array([[ 3494.64,  9157.84],
        [ 9157.84, 30468.89]]))

In [7]:
coef_Pirsona = np.cov(zp, ks,ddof=0) / (np.std(zp) * np.std(ks))
coef_Pirsona

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [8]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [9]:
import pandas as pd

In [18]:
data = {'zp': zp, 'ks': ks}
df = pd.DataFrame(data=data)
df

zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459
5   70  739
6   54  653
7  150  902
8  120  746
9  110  832

In [19]:
df.corr()

zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

### Задание № 2.
Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

**Ответ:**

In [20]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
iq

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

Вычислим границы доверительного интервала с помощью критерия Стьюдента и надёжностью 95%.

In [21]:
from scipy.stats import t

In [26]:
alpha2 = 0.05
np.mean(iq) - t.ppf(1 - alpha2 / 2, len(iq) - 1) * np.std(iq, ddof=1) / np.sqrt(len(iq)), np.mean(iq) + t.ppf(1 - alpha2 / 2, len(iq) - 1) * np.std(iq, ddof=1) / np.sqrt(len(iq))

(110.55608365158724, 125.64391634841274)

### Задание № 3.
Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

**Ответ:**

In [27]:
from scipy.stats import norm

In [31]:
D3 = 25
n3 = 27
alpha3 = 0.05
M3 = 174.2
M3 + norm.ppf(alpha3 / 2) * np.sqrt(D3 / n3), M3 + norm.ppf(1 - alpha3 / 2) * np.sqrt(D3 / n3)

(172.3140237765397, 176.08597622346028)

### Задание № 4.
Выберите тему для проектной работы по курсу Теории вероятностей и математической статистики
и напишите ее в комментарии к Практическому заданию.(ПРОЕКТ ДОБРОВОЛЬНЫЙ)

Описание курсового проекта по предмету Теория вероятностей и математическая статистика

Во второй половине курса студентам даётся проект с темой на выбор. Студентам предлагается общее направление для проекта - исследовать данные с imdb. Для этих данных можно сделать EDA (Exploratory Data Analysis – разведочный анализ данных) либо проверить предложенную самим студентом статистическую гипотезу. При наличии опыта работы с данными и статистикой некоторые студенты также могут взять другую тему - например, исследовать курс биткойна.

В качестве данных студенты могут брать датасеты с информацией с сайта imdb (либо с Kaggle, либо откуда-то из Интернета, эти данные нужно искать самим). Также есть возможность взять любые другие данные, если выбрана другая тема. Работы выполняются с использованием любых методов из вебинаров и методичек по предмету Теория вероятностей и математическая статистика. Это может быть постановка и проверка статистических гипотез, EDA, дисперсионный анализ и т.д.

Готовый проект должен быть выложен на github в аккаунте студента в виде файла с расширением ipynb (Jupyter Notebook), ссылка на проект прикладывается в раздел Задание. Срок выполнения задания - неделя после 8-го вебинара. Начинать можно после 6-го вебинара, после того, как преподаватель одобрит тему (студент указывает тему работы в Задание к вебинару 6).

Ссылка на проект должна быть добавлена студентом к Заданию вебинара 8.

Примеры постановки темы проекта:

Проверить гипотезу: Комедийные фильмы, снятые до 1990 года, в среднем имеют более высокую оценку, чем комедийные фильмы, снятые позже.
Статистическое сопоставление цены биткоина с курсами фиатных активов (USD,EUR,RUR), ценами на нефть, драг металлы или с ценами других криптовалют по отношению к биткойну.
Также студент может до выполнения работы поставить широкий круг задач для проекта и уже в процессе выполнения оставить только то, что вошло в проект.

Пример:

"В проектной работе хотела бы сделать анализ по Странам по данным imbd.com.
По странам рассчитать основные статистические показатели: Мода, медиана, квартили, дисперсию.
Проверить, работает ли нормальное распределение и Паретто.
Проверить есть ли зависимость бюджетов, рейтингов, жанров от страны выпуска фильмов.
Посмотреть поведение стран во времени.
В идеале, хотела бы сделать прогноз на 2020 год: какие страны с какой вероятностью выпустят определенное количество фильмов с определенным бюджетом определенного жанра."


**Ответ:**

Провести разведочный анализ датасета - "https://www.kaggle.com/c/tutors-expected-math-exam-results/overview", проверить ряд гипотез, например зависимость среднего балла ученика на экзамене по математике от предметной специализации репититора, его опыта/квалификации. Построить простейшие предсказательные модели. 